name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setting-up JAVA
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '12.x'

      - name: Setup Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          npm install
          npm install -g firebase-tools

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Build
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
          start: npm run serve
          wait-on: 'http://localhost:5000'
          command-prefix: 'percy exec -- npx'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: 'Change Firebase configuration to live'
        run: |
          PACKAGE_VERSION=$(node -pe "require('./package.json').version")
          sed -r -i 's/(\{\{build_no\}\})/'"$PACKAGE_VERSION"'/' dist/index.html
          sed -r -i 's/(\/firebase-init.js)/\/__\/firebase\/init.js/g' dist/index.html
          rm -rf dist/firebase-init.js

      - name: Upload Live
        run: firebase deploy --force --token ${{ secrets.FIREBASE_TOKEN }}
        id: firebase-production
        if: ${{ github.ref == 'refs/heads/main' }}
